force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Customer&#39;s home country.</description>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer&#39;s product.</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseControllerTest.cls
/*
* @author mostafa-anm
*
* @description Testclass for CaseController.
*/
@isTest
public  class CaseControllerTest {

    /*
    * @description Unit test for getting product information.
    * @returns Nothing.
    */
    @isTest
    public static void testGetProduct() {
        Contact testContact =  new Contact(
            LastName='Last Name',
            Home_Country__c='DE',
            Product__c='Standard');

        insert testContact;

        Case testCase = new Case(
            Subject='Test',
            ContactId=testContact.Id);

        insert testCase;

        Test.startTest();
        Map<String, Object> result = CaseController.getProduct(testCase.Id);
        Test.stopTest();

        // Assert correct product type.
        System.assertEquals('Standard', result.get('productType'));
        // Assert correct results from StandardProduct class.
        System.assertEquals(0, result.get('costPerMonth'));
        System.assertEquals(6, result.get('cardReplacementCost'));
        System.assertEquals(1.7, result.get('atmFeeInOtherCountries'));
    }
}