force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Customer&#39;s home country.</description>
    <label>Home Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Customer&#39;s product.</description>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseController.cls
/*
* @author mostafa-anm
*
* @description Lightning compatible Case controller.
*/
public with sharing class CaseController {

    /*
    * @description Get a product information relevant to a contact.
    * @param caseId The Id to be used to get it's related contact information.
    * @returns Map of product information.
    */
    @AuraEnabled
    public static Map<String, Object> getProduct(Id caseId) {
        Case c = [
            SELECT
                Id,
                Contact.Product__c,
                Contact.Home_Country__c
            FROM
                Case
            WHERE
                Id = :caseId
        ];

        Product p = new Product(c.Contact.Product__c);
        return new Map<String, Object>{
            'productType' => c.Contact.Product__c,
            'costPerMonth' => p.getCostPerMonth(c.Contact.Home_Country__c),
            'cardReplacementCost' => p.getCardReplacementCost(c.Contact.Home_Country__c),
            'atmFeeInOtherCountries' => p.getatmFeeInOtherCountries(c.Contact.Home_Country__c)
        };
    }
}