force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Contact&#39;s language in ISO 639-1 format.</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en</fullName>
                <default>true</default>
                <label>en</label>
            </value>
            <value>
                <fullName>de</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Survey_date__c.field-meta.xml
<CustomField>
    <fullName>Survey_date__c</fullName>
    <description>Stores the date when the next survey should be sent.</description>
    <label>Survey date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduleSendSurveyTest.cls
/**
* @author mostafa-anm
*
* @description Testclass for ScheduleSendSurvey.
*/
@isTest
public class ScheduleSendSurveyTest {

    /*
    * @description Unit test for scheduling ScheduleSendSurvey.
    * @returns Nothing.
    */
    @isTest
    public static void testExecuteSendSurvey() {
        insert new Contact(
            Language__c='en',
            LastName='Last Name',
            FirstName='First Name',
            Email='test@example.com',
            Survey_date__c=Datetime.now().addDays(-1));

        Test.startTest();
        ScheduleSendSurvey scheduler = new ScheduleSendSurvey();
        // Dummy CRON expression daily at 12:00 pm.
        System.schedule('ScheduleSendSurveyTest', '0 0 12 * * ?', scheduler);
        // Since stopTest would execute ScheduleSendSurvey synchronously
        // And SendSurvey is asynchronous so it is not executed and we need to call do that manually.
        scheduler.execute(null);
        Test.stopTest();

        // Expect an email to be sent out.
        System.assertEquals(1, [SELECT count() FROM EmailMessage]);
    }
}